apiVersion: apps/v1beta
kind: Deployment
metadata:
	name: springboot-k8s-deployment
spec:
	selector:
        matchlabels:
            app: springboot-k8s-deployment
        replicas: 3
        templates:
            metadata:
                labels:
                    app: springboot-k8s-deployment
            spec:
                containers:
                - name: springboot-k8s-deployment
                  image: gru.ocir.io/grzjxifl0gp7/webinar-demo/webinario-cicd:latest
                  imagePullPolicy: Always
                  ports:
                  - containerPort: 3000
                imagePullSecrets:
                - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
    name: springboot-k8s-deployment
spec:
    type: NodePort
    ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: springboot-k8s-deployment