apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-deployment-svc
  labels:
    app: springboot-k8s-deployment
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: springboot-k8s-deployment